name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'

      - name: Download Dependencies
        shell: bash
        run: go mod download

      - name: Build
        shell: bash
        run: go build